version: "3"

services:
  web:
    image: losolio/eventuras
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=eventuras_db;Username=eventuras;Password=Str0ng!Pasword"
    ports:
      - "5100:80"
    depends_on:
      db:
        condition: service_healthy

  api:
    image: losolio/eventuras:api
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=eventuras_db;Username=eventuras;Password=Str0ng!Pasword"
    ports:
      - "5101:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: eventuras_db
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eventuras
      POSTGRES_PASSWORD: "Str0ng!Pasword"
      POSTGRES_DB: eventuras_db
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready --dbname=eventuras_db --username=eventuras"]
      interval: 5s
      timeout: 5s
      retries: 10
