version: '3'

services:

  web:
    container_name: eventuras-dev
    image: eventuras:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=Str0ng#PaSsw0rd
      - ACCEPT_EULA=Y