version: '3'

services:

  web:
    image: losolio/eventuras:${TAG:-latest}
    environment:
      ConnectionStrings__DefaultConnection: 'Host=db;Database=eventuras_db;Username=pguser;Password=Str0ngPassword'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5100:80"
    depends_on:
      - db

  db:
    container_name: eventuras_db
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eventuras
      POSTGRES_PASSWORD: 'Str0ng!Pasword'
      POSTGRES_DB: eventuras_db