version: '3'

services:

  web:
    image: losolio/eventuras:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: event_db
    environment:
      - MSSQL_SA_PASSWORD=Str0ng#PaSsw0rd
      - ACCEPT_EULA=Y 