version: '3'

services:

  web:
    image: losolio/eventuras:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5100:80"
    depends_on:
      - db

  db:
    container_name: eventuras_db
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: Str0ngPassword
      POSTGRES_DB: eventuras_db